# This is a config for E2B sandbox template.
# You can use 'template_id' (1db0ceubobh88yem7h90) or 'template_name (super-rag) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='super-rag')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'super-rag' })

dockerfile = "e2b.Dockerfile"
template_name = "super-rag"
template_id = "1db0ceubobh88yem7h90"
